### ISSUE TITLE
Module not found "https://deno.land/std/io/bufio.ts"

### ISSUE THREAD

**Issue by KaKi87** [denyncrawford/dndb#20]
Hello,

@denyncrawford, the following code :

```js
import Datastore from 'https://deno.land/x/dndb@0.3.3/mod.ts'
```

throws the following error :

```
error: Module not found "https://deno.land/std/io/bufio.ts".
    at https://deno.land/x/dndb@0.3.3/deps.ts:5:27
```

@AmateurPotion, since you recently updated your fork, I'm guessing you fixed that, but how to import your module ?

The following code :

```js
import Datastore from 'https://raw.githubusercontent.com/AmateurPotion/dndb/main/mod.ts'
```

throws the following error :

```
error: Relative import path "dndb/executor.ts" not prefixed with / or ./ or ../
    at https://raw.githubusercontent.com/AmateurPotion/dndb/main/src/mod.ts:15:22
```

Thanks

**Comment by DevP0tion** [comment]
I was also in the process of updating because I ran into a similar problem :<

**Comment by DevP0tion** [comment]
@KaKi87 
저는 Import_map.json 을 이용해 가져오기 경로들을 정리했습니다. 해당 상대 경로 문제는 ide의 deno 버전 문제인듯 싶은데 혹시 어떤 ide를 사용하시는 중인지 알려주실 수 있으신가요?

google translate) 
I used Import_map.json to organize the import paths. The relative path problem seems to be a problem with the deno version of the ide. Could you please tell me which ide you are using?

**Comment by KaKi87** [comment]
> The relative path problem seems to be a problem with the deno version

I upgraded to the latest version (`1.27.0`) which doesn't change anything.

Additionally, would you please enable issues on your own repository ?

Thanks

**Comment by KaKi87** [comment]
Hello ?

**Comment by SINE** [comment]
@KaKi87 
@AmateurPotion has done a few changes/cleanups on a forked repo. I have done another fork and fixed some issues with Deno 1.31.2 - Please see if it works for you.
https://github.com/SINE/dndb

**Comment by KaKi87** [comment]
Actually, I got so desperate in the meantime, that I created my own library, and a cross-runtime one : [`xedb`](https://git.kaki87.net/KaKi87/xedb).

Provided without any warranty, especially since there is no unit testing yet, but working for my use case.

Thanks anyway !
